def success():
    sys.exit(0)

# Abnormal termination
def failure():
    print("abnormal termination")
    sys.exit(1)

failure()
